const municipios = [
  { value: "Altamira", nombre: "Altamira" },
  { value: "Arenoso", nombre: "Arenoso" },
  { value: "Azua de Compostela", nombre: "Azua de Compostela" },

  { value: "Baitoa", nombre: "Baitoa" },
  { value: "Bajos de Haina", nombre: "Bajos de Haina" },
  { value: "Baní", nombre: "Baní" },
  { value: "Bánica", nombre: "Bánica" },
  { value: "Barahona", nombre: "Barahona" },
  { value: "Bayaguana", nombre: "Bayaguana" },
  { value: "Boca Chica", nombre: "Boca Chica" },
  { value: "Bohechío", nombre: "Bohechío" },
  { value: "Bonao", nombre: "Bonao" },

  { value: "Cabral", nombre: "Cabral" },
  { value: "Cabrera", nombre: "Cabrera" },
  { value: "Cambita Garabitos", nombre: "Cambita Garabitos" },
  { value: "Castañuelas", nombre: "Castañuelas" },
  { value: "Castillo", nombre: "Castillo" },
  { value: "Cayetano Germosén", nombre: "Cayetano Germosén" },
  { value: "Cevicos", nombre: "Cevicos" },
  { value: "Comendador", nombre: "Comendador" },
  { value: "Constanza", nombre: "Constanza" },
  { value: "Consuelo", nombre: "Consuelo" },
  { value: "Cotuí", nombre: "Cotuí" },
  { value: "Cristóbal", nombre: "Cristóbal" },

  { value: "Dajabón", nombre: "Dajabón" },
  { value: "Distrito Nacional", nombre: "Distrito Nacional" },
  { value: "Duvergé", nombre: "Duvergé" },

  { value: "El Cercado", nombre: "El Cercado" },
  { value: "El Factor", nombre: "El Factor" },
  { value: "El Llano", nombre: "El Llano" },
  { value: "El Peñón", nombre: "El Peñón" },
  { value: "El Pino", nombre: "El Pino" },
  { value: "El Seibo", nombre: "El Seibo" },
  { value: "El Valle", nombre: "El Valle" },
  { value: "Enriquillo", nombre: "Enriquillo" },
  { value: "Esperanza", nombre: "Esperanza" },
  { value: "Estebanía", nombre: "Estebanía" },
  { value: "Eugenio María de Hostos", nombre: "Eugenio María de Hostos" },

  { value: "Fantino", nombre: "Fantino" },
  { value: "Fundación", nombre: "Fundación" },

  { value: "Galván", nombre: "Galván" },
  { value: "Gaspar Hernández", nombre: "Gaspar Hernández" },
  { value: "Guananico", nombre: "Guananico" },
  { value: "Guayabal", nombre: "Guayabal" },
  { value: "Guayacanes", nombre: "Guayacanes" },
  { value: "Guaymate", nombre: "Guaymate" },
  { value: "Guayubín", nombre: "Guayubín" },

  { value: "Hato Mayor", nombre: "Hato Mayor" },
  { value: "Higüey", nombre: "Higüey" },
  { value: "Hondo Valle", nombre: "Hondo Valle" },

  { value: "Imbert", nombre: "Imbert" },

  { value: "Jamao al Norte", nombre: "Jamao al Norte" },
  { value: "Jánico", nombre: "Jánico" },
  { value: "Jaquimeyes", nombre: "Jaquimeyes" },
  { value: "Jarabacoa", nombre: "Jarabacoa" },
  { value: "Jima Abajo", nombre: "Jima Abajo" },
  { value: "Jimaní", nombre: "Jimaní" },
  { value: "Juan de Herrera", nombre: "Juan de Herrera" },
  { value: "Juan Santiago", nombre: "Juan Santiago" },

  { value: "La Ciénaga", nombre: "La Ciénaga" },
  { value: "La Concepción de La Vega", nombre: "La Concepción de La Vega" },
  { value: "La Descubierta", nombre: "La Descubierta" },
  { value: "La Romana", nombre: "La Romana" },
  { value: "Laguna Salada", nombre: "Laguna Salada" },
  { value: "Las Charcas", nombre: "Las Charcas" },
  { value: "Las Guáranas", nombre: "Las Guáranas" },
  { value: "Las Matas de Farfán", nombre: "Las Matas de Farfán" },
  { value: "Las Matas de Santa Cruz", nombre: "Las Matas de Santa Cruz" },
  { value: "Las Salinas", nombre: "Las Salinas" },
  { value: "Las Terrenas", nombre: "Las Terrenas" },
  { value: "Las Yayas de Viajama", nombre: "Las Yayas de Viajama" },
  { value: "Licey al Medio", nombre: "Licey al Medio" },
  { value: "Loma de Cabrera", nombre: "Loma de Cabrera" },
  { value: "Los Alcarrizos", nombre: "Los Alcarrizos" },
  { value: "Los Cacaos", nombre: "Los Cacaos" },
  { value: "Los Hidalgos", nombre: "Los Hidalgos" },
  { value: "Los Ríos", nombre: "Los Ríos" },
  { value: "Luperón", nombre: "Luperón" },

  { value: "Maimón", nombre: "Maimón" },
  { value: "Mao", nombre: "Mao" },
  { value: "Matanzas", nombre: "Matanzas" },
  { value: "Mella", nombre: "Mella" },
  { value: "Miches", nombre: "Miches" },
  { value: "Moca", nombre: "Moca" },
  { value: "Monción", nombre: "Monción" },
  { value: "Monte Cristi", nombre: "Monte Cristi" },
  { value: "Monte Plata", nombre: "Monte Plata" },

  { value: "Nagua", nombre: "Nagua" },
  { value: "Neiba", nombre: "Neiba" },
  { value: "Nizao", nombre: "Nizao" },

  { value: "Oviedo", nombre: "Oviedo" },

  { value: "Padre Las Casas", nombre: "Padre Las Casas" },
  { value: "Paraíso", nombre: "Paraíso" },
  { value: "Partido", nombre: "Partido" },
  { value: "Pedernales", nombre: "Pedernales" },
  { value: "Pedro Brand", nombre: "Pedro Brand" },
  { value: "Pedro Santana", nombre: "Pedro Santana" },
  { value: "Pepillo Salcedo", nombre: "Pepillo Salcedo" },
  { value: "Peralta", nombre: "Peralta" },
  { value: "Peralvillo", nombre: "Peralvillo" },
  { value: "Piedra Blanca", nombre: "Piedra Blanca" },
  { value: "Pimentel", nombre: "Pimentel" },
  { value: "Polo", nombre: "Polo" },
  { value: "Postrer Río", nombre: "Postrer Río" },
  { value: "Pueblo Viejo", nombre: "Pueblo Viejo" },
  { value: "Puerto Plata", nombre: "Puerto Plata" },
  { value: "Puñal", nombre: "Puñal" },

  { value: "Quisqueya", nombre: "Quisqueya" },

  { value: "Ramón Santana", nombre: "Ramón Santana" },
  { value: "Rancho Arriba", nombre: "Rancho Arriba" },
  { value: "Restauración", nombre: "Restauración" },
  { value: "Río San Juan", nombre: "Río San Juan" },

  { value: "Sabana de la Mar", nombre: "Sabana de la Mar" },
  { value: "Sabana Grande de Boyá", nombre: "Sabana Grande de Boyá" },
  { value: "Sabana Grande de Palenque", nombre: "Sabana Grande de Palenque" },
  { value: "Sabana Iglesia", nombre: "Sabana Iglesia" },
  { value: "Sabana Larga", nombre: "Sabana Larga" },
  { value: "Sabana Yegua", nombre: "Sabana Yegua" },
  { value: "Salcedo", nombre: "Salcedo" },
  { value: "Samaná", nombre: "Samaná" },
  { value: "San Antonio de Guerra", nombre: "San Antonio de Guerra" },
  { value: "San Cristóbal", nombre: "San Cristóbal" },
  { value: "San Francisco de Macorís", nombre: "San Francisco de Macorís" },
  { value: "San Gregorio de Nigua", nombre: "San Gregorio de Nigua" },
  { value: "San Ignacio de Sabaneta", nombre: "San Ignacio de Sabaneta" },
  { value: "San José de las Matas", nombre: "San José de las Matas" },
  { value: "San José de los Llanos", nombre: "San José de los Llanos" },
  { value: "San José de Ocoa", nombre: "San José de Ocoa" },
  { value: "San Juan de la Maguana", nombre: "San Juan de la Maguana" },
  { value: "San Pedro de Macorís", nombre: "San Pedro de Macorís" },
  { value: "San Rafael del Yuma", nombre: "San Rafael del Yuma" },
  { value: "San Víctor", nombre: "San Víctor" },
  { value: "Sánchez", nombre: "Sánchez" },
  { value: "Santiago de los Caballeros", nombre: "Santiago de los Caballeros" },
  { value: "Santo Domingo Este", nombre: "Santo Domingo Este" },
  { value: "Santo Domingo Norte", nombre: "Santo Domingo Norte" },
  { value: "Santo Domingo Oeste", nombre: "Santo Domingo Oeste" },
  { value: "Sosúa", nombre: "Sosúa" },

  { value: "Tábara Arriba", nombre: "Tábara Arriba" },
  { value: "Tamayo", nombre: "Tamayo" },
  { value: "Tamboril", nombre: "Tamboril" },
  { value: "Tenares", nombre: "Tenares" },
  { value: "Tireo Arriba", nombre: "Tireo Arriba" },

  { value: "Vallejuelo", nombre: "Vallejuelo" },
  { value: "Vicente Noble", nombre: "Vicente Noble" },
  { value: "Villa Altagracia", nombre: "Villa Altagracia" },
  { value: "Villa Bisonó, Navarrete", nombre: "Villa Bisonó, Navarrete" },
  { value: "Villa Central", nombre: "Villa Central" },
  { value: "Villa González", nombre: "Villa González" },
  { value: "Villa Hermosa", nombre: "Villa Hermosa" },
  { value: "Villa Isabela", nombre: "Villa Isabela" },
  { value: "Villa Jaragua", nombre: "Villa Jaragua" },
  { value: "Villa La Mata", nombre: "Villa La Mata" },
  { value: "Villa Los Almácigos", nombre: "Villa Los Almácigos" },
  { value: "Villa Montellano", nombre: "Villa Montellano" },
  { value: "Villa Riva", nombre: "Villa Riva" },
  { value: "Villa Tapia", nombre: "Villa Tapia" },
  { value: "Villa Vásquez", nombre: "Villa Vásquez" },

  { value: "Yaguate", nombre: "Yaguate" },
  { value: "Yamasá", nombre: "Yamasá" }
];