const paises = [
  
  { value: "Afganistan", nombre: "Afganistán" },
  { value: "Albania", nombre: "Albania" },
  { value: "Alemania", nombre: "Alemania" },
  { value: "Andorra", nombre: "Andorra" },
  { value: "Angola", nombre: "Angola" },
  { value: "Antigua y Barbuda", nombre: "Antigua y Barbuda" },
  { value: "Arabia Saudita", nombre: "Arabia Saudita" },
  { value: "Argelia", nombre: "Argelia" },
  { value: "Argentina", nombre: "Argentina" },
  { value: "Armenia", nombre: "Armenia" },
  { value: "Australia", nombre: "Australia" },
  { value: "Austria", nombre: "Austria" },
  { value: "Azerbaiyan", nombre: "Azerbaiyán" },

  { value: "Bahamas", nombre: "Bahamas" },
  { value: "Bahrein", nombre: "Bahrein" },
  { value: "Bangladesh", nombre: "Bangladés" },
  { value: "Barbados", nombre: "Barbados" },
  { value: "Bielorrusia", nombre: "Bielorrusia" },
  { value: "Belgica", nombre: "Bélgica" },
  { value: "Belice", nombre: "Belice" },
  { value: "Benin", nombre: "Benín" },
  { value: "Bhutan", nombre: "Bután" },
  { value: "Bolivia", nombre: "Bolivia" },
  { value: "Bosnia y Herzegovina", nombre: "Bosnia y Herzegovina" },
  { value: "Botswana", nombre: "Botsuana" },
  { value: "Brasil", nombre: "Brasil" },
  { value: "Brunei", nombre: "Brunéi" },
  { value: "Bulgaria", nombre: "Bulgaria" },
  { value: "Burkina Faso", nombre: "Burkina Faso" },
  { value: "Burundi", nombre: "Burundi" },

  { value: "Cabo Verde", nombre: "Cabo Verde" },
  { value: "Camboya", nombre: "Camboya" },
  { value: "Camerun", nombre: "Camerún" },
  { value: "Canada", nombre: "Canadá" },
  { value: "Catar", nombre: "Catar" },
  { value: "Chad", nombre: "Chad" },
  { value: "Chile", nombre: "Chile" },
  { value: "China", nombre: "China" },
  { value: "Chipre", nombre: "Chipre" },
  { value: "Colombia", nombre: "Colombia" },
  { value: "Comoras", nombre: "Comoras" },
  { value: "Congo", nombre: "Congo" },
  { value: "Corea del Norte", nombre: "Corea del Norte" },
  { value: "Corea del Sur", nombre: "Corea del Sur" },
  { value: "Costa de Marfil", nombre: "Costa de Marfil" },
  { value: "Costa Rica", nombre: "Costa Rica" },
  { value: "Croacia", nombre: "Croacia" },
  { value: "Cuba", nombre: "Cuba" },

  { value: "Dinamarca", nombre: "Dinamarca" },
  { value: "Dominica", nombre: "Dominica" },

  { value: "Ecuador", nombre: "Ecuador" },
  { value: "Egipto", nombre: "Egipto" },
  { value: "El Salvador", nombre: "El Salvador" },
  { value: "Emiratos Arabes Unidos", nombre: "Emiratos Árabes Unidos" },
  { value: "Eritrea", nombre: "Eritrea" },
  { value: "Eslovaquia", nombre: "Eslovaquia" },
  { value: "Eslovenia", nombre: "Eslovenia" },
  { value: "España", nombre: "España" },
  { value: "Estados Unidos", nombre: "Estados Unidos" },
  { value: "Estonia", nombre: "Estonia" },
  { value: "Eswatini", nombre: "Esuatini" },
  { value: "Etiopia", nombre: "Etiopía" },

  { value: "Fiji", nombre: "Fiyi" },
  { value: "Filipinas", nombre: "Filipinas" },
  { value: "Finlandia", nombre: "Finlandia" },
  { value: "Francia", nombre: "Francia" },

  { value: "Gabon", nombre: "Gabón" },
  { value: "Gambia", nombre: "Gambia" },
  { value: "Georgia", nombre: "Georgia" },
  { value: "Ghana", nombre: "Ghana" },
  { value: "Granada", nombre: "Granada" },
  { value: "Grecia", nombre: "Grecia" },
  { value: "Guatemala", nombre: "Guatemala" },
  { value: "Guinea", nombre: "Guinea" },
  { value: "Guinea-Bisau", nombre: "Guinea-Bisáu" },
  { value: "Guinea Ecuatorial", nombre: "Guinea Ecuatorial" },
  { value: "Guyana", nombre: "Guyana" },

  { value: "Haiti", nombre: "Haití" },
  { value: "Honduras", nombre: "Honduras" },
  { value: "Hungria", nombre: "Hungría" },

  { value: "India", nombre: "India" },
  { value: "Indonesia", nombre: "Indonesia" },
  { value: "Irak", nombre: "Irak" },
  { value: "Iran", nombre: "Irán" },
  { value: "Irlanda", nombre: "Irlanda" },
  { value: "Islandia", nombre: "Islandia" },
  { value: "Islas Marshall", nombre: "Islas Marshall" },
  { value: "Islas Salomon", nombre: "Islas Salomón" },
  { value: "Israel", nombre: "Israel" },
  { value: "Italia", nombre: "Italia" },

  { value: "Jamaica", nombre: "Jamaica" },
  { value: "Japon", nombre: "Japón" },
  { value: "Jordania", nombre: "Jordania" },

  { value: "Kazajistan", nombre: "Kazajistán" },
  { value: "Kenia", nombre: "Kenia" },
  { value: "Kirguistan", nombre: "Kirguistán" },
  { value: "Kiribati", nombre: "Kiribati" },
  { value: "Kuwait", nombre: "Kuwait" },

  { value: "Laos", nombre: "Laos" },
  { value: "Lesoto", nombre: "Lesoto" },
  { value: "Letonia", nombre: "Letonia" },
  { value: "Libano", nombre: "Líbano" },
  { value: "Liberia", nombre: "Liberia" },
  { value: "Libia", nombre: "Libia" },
  { value: "Liechtenstein", nombre: "Liechtenstein" },
  { value: "Lituania", nombre: "Lituania" },
  { value: "Luxemburgo", nombre: "Luxemburgo" },

  { value: "Madagascar", nombre: "Madagascar" },
  { value: "Malasia", nombre: "Malasia" },
  { value: "Malaui", nombre: "Malaui" },
  { value: "Maldivas", nombre: "Maldivas" },
  { value: "Mali", nombre: "Malí" },
  { value: "Malta", nombre: "Malta" },
  { value: "Marruecos", nombre: "Marruecos" },
  { value: "Mauricio", nombre: "Mauricio" },
  { value: "Mauritania", nombre: "Mauritania" },
  { value: "Mexico", nombre: "México" },
  { value: "Micronesia", nombre: "Micronesia" },
  { value: "Moldavia", nombre: "Moldavia" },
  { value: "Monaco", nombre: "Mónaco" },
  { value: "Mongolia", nombre: "Mongolia" },
  { value: "Montenegro", nombre: "Montenegro" },
  { value: "Mozambique", nombre: "Mozambique" },
  { value: "Myanmar", nombre: "Myanmar" },

  { value: "Namibia", nombre: "Namibia" },
  { value: "Nauru", nombre: "Nauru" },
  { value: "Nepal", nombre: "Nepal" },
  { value: "Nicaragua", nombre: "Nicaragua" },
  { value: "Niger", nombre: "Níger" },
  { value: "Nigeria", nombre: "Nigeria" },
  { value: "Noruega", nombre: "Noruega" },
  { value: "Nueva Zelanda", nombre: "Nueva Zelanda" },

  { value: "Oman", nombre: "Omán" },

  { value: "Paises Bajos", nombre: "Países Bajos" },
  { value: "Pakistan", nombre: "Pakistán" },
  { value: "Palaos", nombre: "Palaos" },
  { value: "Palestina", nombre: "Palestina" },
  { value: "Panama", nombre: "Panamá" },
  { value: "Papua Nueva Guinea", nombre: "Papúa Nueva Guinea" },
  { value: "Paraguay", nombre: "Paraguay" },
  { value: "Peru", nombre: "Perú" },
  { value: "Polonia", nombre: "Polonia" },
  { value: "Portugal", nombre: "Portugal" },

  { value: "Reino Unido", nombre: "Reino Unido" },
  { value: "Republica Centroafricana", nombre: "República Centroafricana" },
  { value: "Republica Checa", nombre: "República Checa" },
  {
    value: "Republica Democratica del Congo",
    nombre: "República Democrática del Congo",
  },
  { value: "Republica Dominicana", nombre: "República Dominicana" },
  { value: "Rumania", nombre: "Rumanía" },
  { value: "Rusia", nombre: "Rusia" },
  { value: "Ruanda", nombre: "Ruanda" },

  { value: "Samoa", nombre: "Samoa" },
  { value: "San Cristobal y Nieves", nombre: "San Cristóbal y Nieves" },
  { value: "San Marino", nombre: "San Marino" },
  {
    value: "San Vicente y las Granadinas",
    nombre: "San Vicente y las Granadinas",
  },
  { value: "Santa Lucia", nombre: "Santa Lucía" },
  { value: "Santo Tome y Principe", nombre: "Santo Tomé y Príncipe" },
  { value: "Senegal", nombre: "Senegal" },
  { value: "Serbia", nombre: "Serbia" },
  { value: "Seychelles", nombre: "Seychelles" },
  { value: "Sierra Leona", nombre: "Sierra Leona" },
  { value: "Singapur", nombre: "Singapur" },
  { value: "Siria", nombre: "Siria" },
  { value: "Somalia", nombre: "Somalia" },
  { value: "Sri Lanka", nombre: "Sri Lanka" },
  { value: "Sudafrica", nombre: "Sudáfrica" },
  { value: "Sudan", nombre: "Sudán" },
  { value: "Sudan del Sur", nombre: "Sudán del Sur" },
  { value: "Suecia", nombre: "Suecia" },
  { value: "Suiza", nombre: "Suiza" },
  { value: "Surinam", nombre: "Surinam" },

  { value: "Tailandia", nombre: "Tailandia" },
  { value: "Taiwan", nombre: "Taiwán" },
  { value: "Tanzania", nombre: "Tanzania" },
  { value: "Tayikistan", nombre: "Tayikistán" },
  { value: "Timor Oriental", nombre: "Timor Oriental" },
  { value: "Togo", nombre: "Togo" },
  { value: "Tonga", nombre: "Tonga" },
  { value: "Trinidad y Tobago", nombre: "Trinidad y Tobago" },
  { value: "Tunez", nombre: "Túnez" },
  { value: "Turkmenistan", nombre: "Turkmenistán" },
  { value: "Turquia", nombre: "Turquía" },
  { value: "Tuvalu", nombre: "Tuvalu" },

  { value: "Ucrania", nombre: "Ucrania" },
  { value: "Uganda", nombre: "Uganda" },
  { value: "Uruguay", nombre: "Uruguay" },
  { value: "Uzbekistan", nombre: "Uzbekistán" },

  { value: "Vanuatu", nombre: "Vanuatu" },
  { value: "Vaticano", nombre: "Vaticano" },
  { value: "Venezuela", nombre: "Venezuela" },
  { value: "Vietnam", nombre: "Vietnam" },

  { value: "Yemen", nombre: "Yemen" },
  { value: "Yibuti", nombre: "Yibuti" },

  { value: "Zambia", nombre: "Zambia" },
  { value: "Zimbabue", nombre: "Zimbabue" },
];