const sectores = [
  { value: "Piantini", nombre: "Piantini" },
  { value: "Naco", nombre: "Naco" },
  { value: "Bella Vista", nombre: "Bella Vista" },
  { value: "Evaristo Morales", nombre: "Evaristo Morales" },
  { value: "Gazcue", nombre: "Gazcue" },
  { value: "Zona Colonial", nombre: "Zona Colonial" },
  { value: "Los Cacicazgos", nombre: "Los Cacicazgos" },
  { value: "El Millón", nombre: "El Millón" },
  { value: "Arroyo Hondo", nombre: "Arroyo Hondo" },
  { value: "Los Ríos", nombre: "Los Ríos" },
  { value: "Mirador Norte", nombre: "Mirador Norte" },
  { value: "Mirador Sur", nombre: "Mirador Sur" },
  { value: "La Esperilla", nombre: "La Esperilla" },
  { value: "Ensanche Naco", nombre: "Ensanche Naco" },
  { value: "Ensanche Paraíso", nombre: "Ensanche Paraíso" },
  { value: "Ensanche Quisqueya", nombre: "Ensanche Quisqueya" },
  { value: "Ensanche Ozama", nombre: "Ensanche Ozama" },
  { value: "Villa Consuelo", nombre: "Villa Consuelo" },
  { value: "Villa Juana", nombre: "Villa Juana" },
  { value: "Villa María", nombre: "Villa María" },
  { value: "San Carlos", nombre: "San Carlos" },
  { value: "Los Prados", nombre: "Los Prados" },
  { value: "Julieta", nombre: "Julieta" },
  { value: "La Julia", nombre: "La Julia" },
  { value: "El Vergel", nombre: "El Vergel" },
  { value: "Los Restauradores", nombre: "Los Restauradores" },
  { value: "La Castellana", nombre: "La Castellana" },
  { value: "Cristo Rey", nombre: "Cristo Rey" },
  { value: "Capotillo", nombre: "Capotillo" },
  { value: "Los Guandules", nombre: "Los Guandules" },
  { value: "Gualey", nombre: "Gualey" },
  { value: "La Zurza", nombre: "La Zurza" },
  { value: "Simón Bolívar", nombre: "Simón Bolívar" },
  { value: "Villa Francisca", nombre: "Villa Francisca" },
  { value: "San Gerónimo", nombre: "San Gerónimo" },
  { value: "Honduras", nombre: "Honduras" },
  { value: "Los Jardines", nombre: "Los Jardines" },
  { value: "Alma Rosa", nombre: "Alma Rosa" },
  { value: "Los Mina", nombre: "Los Mina" },
  { value: "Sabana Perdida", nombre: "Sabana Perdida" },
  { value: "Villa Mella", nombre: "Villa Mella" },
  { value: "Invivienda", nombre: "Invivienda" },
  { value: "Herrera", nombre: "Herrera" },
  { value: "Manoguayabo", nombre: "Manoguayabo" },
  { value: "Los Alcarrizos", nombre: "Los Alcarrizos" },
  { value: "Km 9", nombre: "Km 9" },
  { value: "Buenos Aires", nombre: "Buenos Aires" },
  { value: "Cancino", nombre: "Cancino" },
  { value: "Guaricano", nombre: "Guaricano" },
  { value: "24 de Abril", nombre: "24 de Abril" },
  { value: "San Juan Bosco", nombre: "San Juan Bosco" }
];